## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - 0.6
os:
  - linux
  - osx
env:
  - GROUP=Examples
notifications:
  email: false
script:
- julia --check-bounds=yes -e 'Pkg.update();
          Pkg.clone(pwd(), "PlotlyJSFactory");
          Pkg.build("PlotlyJSFactory");
          Pkg.add("NBInclude");
          Pkg.build("NBInclude");
          Pkg.add("JLD");
          Pkg.build("JLD");
          using NBInclude;
          if ENV["GROUP"] == "Examples"
            nbinclude(Pkg.dir("PlotlyJSFactory")*"/examples/chord_plot.ipynb")
          else
                println("Unknown test command.")
          end'